function OverrideValveModule(valveID, valveDuration)

sma = NewStateMachine();
sma = AddState(sma, 'Name', 'ValveOpen', ...
'Timer', valveDuration,...
'StateChangeConditions', {'Tup', 'ValveClose'},...
'OutputActions', {'ValveModule1', ['O' valveID]});

sma = AddState(sma, 'Name', 'ValveClose', ...
'Timer', 0,...
'StateChangeConditions', {'Tup', 'Exit'},...
'OutputActions', {'ValveModule1', ['C' valveID]});
SendStateMachine(sma);
RawEvents = RunStateMachine;